CREATE DATABASE IF NOT EXISTS blog;

CREATE TABLE IF NOT EXISTS posts (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  body MEDIUMTEXT NOT NULL,
  dateAndTime DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS comment (
  post_id PRIMARY KEY FOREIGN KEY REFERENCES post.id,
  id INT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  dateAndTime DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS admin (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL
);